### ISSUE TITLE
Minor Bug: arm library is used on intel platforms

### ISSUE THREAD

**Issue by grasshide** [CDrummond/music-similarity#4]
/usr/bin/python3 /opt/music-similarity/music-similarity.py --log-level INFO --test -c /opt/music-similarity/myconfig.json
2022-05-26 17:11:13 I Testing musly
2022-05-26 17:11:13 E Failed to open Musly shared library (/opt/music-similarity/linux/armv7l/libmusly.so)!

**Comment by CDrummond** [comment]
If you save the following to `test.py`:
```
import platform
print("%s" % platform.processor())
```
...then run `python test.py` - what does it print?

p.s. I have stopped using this, as I prefer the bliss mixer instead.

**Comment by grasshide** [comment]
I'm so confused. There are so many plugins and I'm not sure how they all play together. By "bliss mixer" you mean you use this server with bliss? I also only use bliss.
`  "bliss":{
    "enabled":true,
    "analyser":"linux/x86-64/bliss-analyse"
  }`

I did the work to get this server running in Docker. Sorry, I should have mentioned that. The printout you suggested is empty. 

The Dockerfile is here https://pastebin.com/EUYL9Yb9 in case you're interested. I use the lms docker community image and did not want to change anything there. So I run this in its own container.

**Comment by CDrummond** [comment]
Well, the printout being empty implies Python could not detect the processor - so falls back to arm, which fails for you.

By bliss I mean https://forums.slimdevices.com/showthread.php?116068-Announce-Bliss-DSTM-mixer

**Comment by CDrummond** [comment]
You can manually set the path to musly using the config: https://raw.githubusercontent.com/CDrummond/music-similarity/master/docs/OtherConfig.md
